cors:
  originPatterns: http://localhost:8080,http://localhost:3000
file:
  upload-dir: C:\WorkAndStudy\Estudos\Curso Udemy\REST API's RESTFul do 0 à AWS c. Spring Boot 3 Java e Docker\secao7\uploads
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/curso-udemy
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  servlet:
     multipart:
       enabled: true
       file-size-threshold: 2KB
       max-file-size: 200MB
       max-request-size: 215MB
springdoc:
  pathsToMatch: /api/**,/auth
  swagger-ui:
    use-root-path: true